# Generated by Django 2.2.1 on 2019-05-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_github_marketplace', '0002_update_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='sender',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
