# Generated by Django 3.1.1 on 2020-09-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_github_marketplace', '0003_sender_email_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payload',
            field=models.JSONField(),
        ),
    ]
