# Generated by Django 4.2.12 on 2024-05-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcms_github_marketplace", "0007_manualpurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="gitops_prefix",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
    ]
