FROM hub.kiwitcms.eu/kiwitcms/enterprise

COPY ./dist/*.whl /Kiwi/dist/
ARG PKG_TOKEN
RUN pip install --no-cache-dir --find-links /Kiwi/dist/ \
    --index-url https://$PKG_TOKEN@pkg.kiwitcms.eu/pypi/ \
    --extra-index-url https://pypi.org/simple/ \
    /Kiwi/dist/kiwitcms_github_marketplace*.whl
